infNineS =Global.getVar('infNineS')
infFourM =Global.getVar('infFourM')
infCnn =Global.getVar('infCnn')
infPlDc =Global.getVar('infPlDc')
infCdyld =Global.getVar('infCdyld')
infVeS =Global.getVar('infNineS')
infCnn =Global.getVar('infCnn')
infPlDc =Global.getVar('infPlDc')
infVlnDk =Global.getVar('infVlnDk')
infOneHr =Global.getVar('infOneHr')
preSel =Global.getVar('preSel')
disVInst =Global.getVar('disVInst')
disRef =Global.getVar('disRef')
disPow =Global.getVar('disPow')
disFtTk =Global.getVar('disFtTk')
dVilSelc =Global.getVar('dVilSelc')
disCaud =Global.getVar('disCaud')
disStr =Global.getVar('disStr')
disGob =Global.getVar('disGob')
mouseBot =Global.getVar('mouseBot')
marVInst =Global.getVar('marvInst')
marRef =Global.getVar('marRef')
marPow =Global.getVar('marPow')
marVaul =Global.getVar('marVaul')
maStrTk =Global.getVar('maStrTk')
marStVa =Global.getVar('marStVa')
mVilSelc =Global.getVar('mVilSelc')
marFtSel =Global.getVar('marFtSel')
marDek =Global.getVar('marDek')
cusSelc =Global.getVar('cusSelc')
cusRef =Global.getVar('cusRef')
starCha =Global.getVar('starCha')
starStr =Global.getVar('starStr')
starCrd =Global.getVar('starCrd')
starAmb =Global.getVar('starAmb')
starRef =Global.getVar('starRef')
starInst =Global.getVar('starInst')
starSelc =Global.getVar('starSelc')
aniInst =Global.getVar('aniInst')
aniPlus =Global.getVar('aniPlus')
aniMinus =Global.getVar('aniMinus')
aniShow =Global.getVar('aniShow')
aniSelc =Global.getVar('aniSelc')
aniFate =Global.getVar('aniFate')
aniRef =Global.getVar('aniRef')

disney_list = {
  {name="Despicable Plots", url="http://cloud-3.steamusercontent.com/ugc/1782840181541265526/91FF05F376369260ECA081822A0D4EDDB04A3C72/"},
  {name="Bigger and Badder", url="http://cloud-3.steamusercontent.com/ugc/1822276928232865079/D0E9554BA417D2A2B264A47D02691902B823C89A/"},
  {name="Evil Comes Prepared", url="http://cloud-3.steamusercontent.com/ugc/1782840181541267477/BCC0F2235A546C268EA0019ACC287266283BD0E7/"},
  {name="Perfectly Wretched", url="http://cloud-3.steamusercontent.com/ugc/1699529613851492778/3C87069D1A4EE232BA9F23567817EECB1CE40042/"},
  {name="The Worst Takes it All", url="http://cloud-3.steamusercontent.com/ugc/1782840181541276129/24929ED7934DC4D5833070D86D0F71CB30D7A097/"},
  {name="Wicked to the Core", url="http://cloud-3.steamusercontent.com/ugc/1782840181541277144/74D3420D57F7C1BA0C70A7C27003212EE1054636/"},
  {name="", url=""},
}

marvel_list = {
  {name="Infinite Power", url="http://cloud-3.steamusercontent.com/ugc/1782840181541271301/A521640864CE3E63FDED319BB3FDEED87AA888F1/"},
  {name="Mischief Malice", url="http://cloud-3.steamusercontent.com/ugc/1782840181541272717/7F11C72D4333D9DC3448D0C1D16FE73AFEFECFA5/"},
  {name="We are Venom", url="http://cloud-3.steamusercontent.com/ugc/1793018747653914063/3676A136250B7491571CD87D3919F3ECA4264A84/"},
  {name="Twisted Ambitions", url="http://cloud-3.steamusercontent.com/ugc/1793018747653914063/3676A136250B7491571CD87D3919F3ECA4264A84/"},
  {name="", url=""},
}

star_list = {
  {name="Power of the Dark Side", url="http://cloud-3.steamusercontent.com/ugc/1822276928233573514/A35DB28D338CAB1936C0A84FAF6F107F93B496D4/"},
  {name="Scum and Villainy", url="http://cloud-3.steamusercontent.com/ugc/1822276928233573514/A35DB28D338CAB1936C0A84FAF6F107F93B496D4/"},
  {name="", url=""},
}

customs_list = {
  {name="Dark & Edgy", url="http://cloud-3.steamusercontent.com/ugc/1842530654448748915/B40BCF0E8BF8E29454E93E5D6914D873A48C105C/"},
  {name="Advanced Calculations", url="http://cloud-3.steamusercontent.com/ugc/1842530654448748639/E853D3E4198BF44E9825361C6E717A42D676792E/"},
  {name="Hostile Takeover", url="http://cloud-3.steamusercontent.com/ugc/1842530654448750065/F1B50484774248B4A4D993968755CF0266561744/"},
  {name="Root of Corruption", url="http://cloud-3.steamusercontent.com/ugc/1842530654448750758/FD2D318056E65D8FAF9B8359C9CE6ECF2DABFA07/"},
  {name="Fire with Fire", url="http://cloud-3.steamusercontent.com/ugc/1753581023981663830/0AD4242BFB4DE3A914E4EDFF9E9A7525F08526B4/"},
  {name="On Razors Edge", url="http://cloud-3.steamusercontent.com/ugc/1842530654448750360/C49AFC05B34B905007F389F307C211F40D181452/"},
  {name="Monsters and Men", url="http://cloud-3.steamusercontent.com/ugc/1842530654448750207/2BC88ABCB580B3D4FC2F97AD912B8910AC582228/"},
  {name="Dreamland Nightmares", url="http://cloud-3.steamusercontent.com/ugc/1842530654448749146/288CEA39CA7EBA016874BB18A845C3A45A0803C8/"},
  {name="Dirty Money", url="http://cloud-3.steamusercontent.com/ugc/1842530654448749048/C91D912679A30E9B24AAB87501FFF263982FFDD6/"},
  {name="From the Shadows", url="http://cloud-3.steamusercontent.com/ugc/1842530654448749271/E4324324A8EAFA7E364DBBFAECEB8BCE3DA6109F/"},
  {name="Ham, Eggs, Spam", url="http://cloud-3.steamusercontent.com/ugc/1842530654448749457/AADCDC61420581E95B7F4BCD0CA38EE4C6C97D9B/"},
  {name="Dark & Edgy", url="http://cloud-3.steamusercontent.com/ugc/1842530654448748915/B40BCF0E8BF8E29454E93E5D6914D873A48C105C/"},
  {name="Parental Advisory", url="http://cloud-3.steamusercontent.com/ugc/1842530654448750455/35CB57E87107267D6A6D2388D07171AE9F624274/"},
  {name="Completely Expected", url="http://cloud-3.steamusercontent.com/ugc/1842530654448748820/543231225364555FD8485D3CB5E793E63FBF9CDE/"},
  {name="Red-handed", url="http://cloud-3.steamusercontent.com/ugc/1842530654448750568/743D2921FA5A7B5F62F7470580C8641E1FFECEDC/"},
  {name="Chaos and Control", url="http://cloud-3.steamusercontent.com/ugc/1842530654448748718/C0C42CDBD1E5446F2C10C8859E04F445F87F8D4C/"},
  {name="Code of Conduct", url="http://cloud-3.steamusercontent.com/ugc/1840283540522674203/8C376A4ABAA3864496A70D9D8547D6410D6E903C/"},
  {name="Secret Recipe", url="http://cloud-3.steamusercontent.com/ugc/1842550789977504138/BF9913769EEEC77057CA11CFB83642B7A407DC1E/"},
  {name="", url=""},
}

anime_list = {
  {name="Battle Begins", url="https://cdn.discordapp.com/attachments/991989912293355540/995307942549139536/battlebeginsart.png"},
  {name="", url=""},
}

function onLoad()
  isOpen = false
  setupButt = "Open Game Setup"
  gamePickButtonGo()
  self.interactable = false
end

function gamePickButtonGo()
    isOpen = false
    self.createButton({click_function="drawUI", function_owner=self,
    position={0,0,0}, rotation={90,0,90}, width=350, height=350,
    tooltip=setupButt})
    self.createButton({click_function="drawUI", function_owner=self,
    position={0,0,0}, rotation={0,90,0}, width=345, height=345,
    tooltip=setupButt})
end

function drawUI()
    if (isOpen ~= true) then
    setupButt = "Close Game Setup"
    self.clearButtons()
    gamePickButtonGo()
    local tooltip1="Spawn Disney Villainous"
    local tooltip2="Spawn Marvel Villainous"
    local tooltip3="Spawn Star Wars Villainous"
    local tooltip4="Spawn Custom Villains"
    local tooltip5="Toggle Extra Options"
    self.createButton({click_function="spawnDis", function_owner=self,
        position={0,0,-2.5}, rotation={0,180,0}, width=1500, height=440,
        color={0,.75,0}, font_size=150, tooltip=tooltip1, label="Disney Villainous"})
    self.createButton({click_function="spawnMar", function_owner=self,
        position={0,0,-3.5}, rotation={0,180,0}, width=1500, height=440,
        color={1,1,0}, font_size=150, tooltip=tooltip2, label="Marvel Villainous"})
    self.createButton({click_function="spawnStar", function_owner=self,
        position={0,0,-4.5}, rotation={0,180,0}, width=1500, height=440,
        color={0.15,0.25,0.9}, font_size=150, tooltip=tooltip3, label="Star Wars Villainous"})
    self.createButton({click_function="listCus", function_owner=self,
        position={0,0,-5.5}, rotation={0,180,0}, width=1500, height=440,
        color={0.625,0.125,0.9375}, font_size=150, tooltip=tooltip4, label="     Custom Villains  ▶"})
    self.createButton({click_function="listOpt", function_owner=self,
        position={0,0,-6.5}, rotation={0,180,0}, width=1500, height=440,
        color={1,1,1}, font_size=150, tooltip=tooltip5, label="◀   Extra Options      "})
    isOpen = true
    else
    self.clearButtons()
    setupButt = "Open Game Setup"
    gamePickButtonGo()
    end
end

function listOpt()
    if (isList ~= true) then
    self.clearButtons()
    gamePickButtonGo()
    drawUI()
    local tooltip21="Spawn Competitive Assets"
    local tooltip22="Reset Hands"
    local tooltip23="Reduce Objects"
    local tooltip24="Selector Presets"
    self.createButton({click_function="spawnCom", function_owner=self,
        position={2.7,0,-3.5}, rotation={0,180,0}, width=1000, height=440,
        color={0,1,1}, font_size=150, tooltip=tooltip21, label="Competitive\nAssets"})
    self.createButton({click_function="resetHands", function_owner=self,
        position={2.7,0,-4.5}, rotation={0,180,0}, width=1000, height=440,
        color={1,0,0}, font_size=150, tooltip=tooltip22, label="Reset\nHands"})
    self.createButton({click_function="clearRoom", function_owner=self,
        position={2.7,0,-5.5}, rotation={0,180,0}, width=1000, height=440,
        color={1,0.5,0}, font_size=150, tooltip=tooltip23, label="Reduce\nObjects"})
    self.createButton({click_function="preSelect", function_owner=self,
        position={2.7,0,-6.5}, rotation={0,180,0}, width=1000, height=440,
        color={0.95703125,0.4375,0.8046875}, font_size=150, tooltip=tooltip24, label="Selector\nPresets"})
    isList = true
    else
    self.clearButtons()
    gamePickButtonGo()
    drawUI()
    isList = false
      end
  end

function listCus()
    if (isCus ~= true) then
    self.clearButtons()
    gamePickButtonGo()
    drawUI()
    local tooltip11="Disney Customs"
    local tooltip12="Anime Villainous"
    self.createButton({click_function="spawnDCus", function_owner=self,
        position={-2.7,0,-4.5}, rotation={0,180,0}, width=1000, height=440,
        color={0,.75,0}, font_size=150, tooltip=tooltip21, label="Disney\nCustoms"})
    self.createButton({click_function="spawnAnime", function_owner=self,
        position={-2.7,0,-5.5}, rotation={0,180,0}, width=1000, height=440,
        color={1,0,0}, font_size=150, tooltip=tooltip22, label="Anime\nVillainous"})
    isCus = true
    else
    self.clearButtons()
    gamePickButtonGo()
    drawUI()
    isCus = false
      end
end

function clearTable()
    isCus = false
    isList = false
    resetHands()
    local clear = getObjectFromGUID('5b9b72').getObjects()
    for k,v in pairs(clear) do
        v.destruct()
    end
    self.clearButtons()
    isOpen = false
    gamePickButtonGo()
    setNotes("")
end

function clearRoom()
    isList = false
    local clear = getObjectFromGUID('7dea6b').getObjects()
    for k,v in pairs(clear) do
        v.destruct()
    end
    local clear = getObjectFromGUID('4c52e4').getObjects()
    for k,v in pairs(clear) do
        v.destruct()
    end
    local clear = getObjectFromGUID('cfc969').getObjects()
    for k,v in pairs(clear) do
        v.destruct()
    end
    local clear = getObjectFromGUID('91d4e2').getObjects()
    for k,v in pairs(clear) do
        v.destruct()
    end
    local clear = getObjectFromGUID('a5af08').getObjects()
    for k,v in pairs(clear) do
        v.destruct()
    end
    self.clearButtons()
    isOpen = false
    gamePickButtonGo()
    setNotes("")
end

function onSave()
  if getObjectFromGUID('640767') then self.destruct() flipTable() else end
  if getObjectFromGUID('58cf0e') then self.destruct() flipTable() else end
  if getObjectFromGUID('26d90b') then self.destruct() flipTable() else end
  if getObjectFromGUID('4171a8') then self.destruct() flipTable() else end
  if getObjectFromGUID('f0d1ab') then self.destruct() flipTable() else end
  if getObjectFromGUID('969a40') then self.destruct() flipTable() else end
  if getObjectFromGUID('aa6cc8') then self.destruct() flipTable() else end
  if getObjectFromGUID('2d1127') then self.destruct() flipTable() else end
  if getObjectFromGUID('e1cc65') then self.destruct() flipTable() else end
  if getObjectFromGUID('f2911c') then self.destruct() flipTable() else end
  if getObjectFromGUID('a2c6cf') then self.destruct() flipTable() else end
  if getObjectFromGUID('32edd2') then self.destruct() flipTable() else end
  if getObjectFromGUID('8f421b') then self.destruct() flipTable() else end
  if getObjectFromGUID('53b36e') then self.destruct() flipTable() else end
  if getObjectFromGUID('e86276') then self.destruct() flipTable() else end
  if getObjectFromGUID('f81448') then self.destruct() flipTable() else end
  if getObjectFromGUID('4bd7b5') then self.destruct() flipTable() else end
  if getObjectFromGUID('7cbc78') then self.destruct() flipTable() else end
  if getObjectFromGUID('61e769') then self.destruct() flipTable() else end
  if getObjectFromGUID('8b9903') then self.destruct() flipTable() else end
  if getObjectFromGUID('af4373') then self.destruct() flipTable() else end
end

function spawnDis()
    setupButt = "Open Game Setup"
    clearTable()
    tableDisney()
    obj = getObjectFromGUID(dVilSelc)
    x = obj.takeObject({rotation={0,180,0},
    position={0.00, 1.55, 0.00},smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(disVInst)
    x = obj.takeObject({rotation={0,270,0}, position={36.5, 1.48, 0.00},smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(disPow)
    x = obj.takeObject({rotation={46.17, 152.14, 319.13}, position={13.70, 3.10, -1.09}, smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(disCaud)
    x = obj.takeObject({rotation={0.00, 290.00, 0.00}, position={14, 1.585, 0.00}, smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(disStr)
    x = obj.takeObject({rotation={0.00, 40.00, 0.00}, position={-13.35, 4.0, -0.25},smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(disGob)
    x = obj.takeObject({rotation={0.00, 180.00, 0.00},position={-13.00, 1.07, 0.00},smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(disFtTk)
    obj.takeObject({rotation={0,270,0}, position={37, 1.74, 0},smooth=false})
    die = getObjectFromGUID(infPlDc)
    die.takeObject({position={37, 2.46, 0},smooth=false})
    obj = getObjectFromGUID(infCdyld)
    x = obj.takeObject({rotation={0,270,0},
    position={33.25, 1.75, 0}, smooth=false})
    obj = getObjectFromGUID(disRef)
    x = obj.takeObject({rotation={0,270,0},
    position={27.50, 1.48, 0.00}, smooth=false})
    x.setLock(true)

end

function spawnMar()
    setupButt = "Open Game Setup"
    clearTable()
    tableMarvel()
    obj = getObjectFromGUID(mVilSelc)
    x = obj.takeObject({position={0,1.55,0},smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(marVInst)
    x = obj.takeObject({rotation={0,270,0},position={45,1.48,0},smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(marRef)
    x = obj.takeObject({rotation={0,270,0},position={36,1.48,0},smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(marPow)
    x = obj.takeObject({position={9.29, 3.56, 0.17},rotation={353.74, 185.05, 173.10},smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(marVaul)
    x = obj.takeObject({position={9.7,1.28,0},smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(maStrTk)
    x = obj.takeObject({position={-9.28, 3.2, -0.72},rotation={7.25, 183.42, 173.09},smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(marStVa)
    x = obj.takeObject({position={-9.7,1.28,0},rotation={0,270,0},smooth=false})
    x.setLock(true)
    die = getObjectFromGUID(infPlDc)
    die.takeObject({position={27.5,2.15,0},smooth=false})
    obj = getObjectFromGUID(infCdyld)
    x = obj.takeObject({rotation={0,270,0},position={31, 1.49,0}, smooth=false})
    obj = getObjectFromGUID(marFtSel)
    x = obj.takeObject({position={0.00, 1.48, -5.30}, rotation={0,180,0},smooth=false})
    x.setLock(true)
    printToAll(" \n \n \n Select which boxes' Common Fate Decks\n you would like to use, by selecting the\n respective Heroes and maybe Events desired.\n \n When Venom's Hero card is selected, he \n will always be included in the Fate deck.\n \n")

end

function spawnStar()
    setupButt = "Open Game Setup"
    clearTable()
    tableStar()
    obj = getObjectFromGUID(starSelc)
    x = obj.takeObject({rotation={0,180,0}, position={0.00, 1.63, 0.00},smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(starInst)
    x = obj.takeObject({rotation={0,270,0}, position={36.5, 1.48, 0.00},smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(starCha)
    x = obj.takeObject({position={17, 2.07, 0}, smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(starCrd)
    x = obj.takeObject({position={16.96, 1.30, 0.08}, smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(starStr)
    x = obj.takeObject({position={16.98, 1.30, -0.41},smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(starAmb)
    x = obj.takeObject({position={17.27, 1.30, 0.12},smooth=false})
    x.setLock(true)
    die = getObjectFromGUID(infPlDc)
    die.takeObject({position={35.00, 2.34, 0},smooth=false})
    obj = getObjectFromGUID(infCdyld)
    x = obj.takeObject({rotation={0,270,0}, position={39.00, 1.68, 0}, smooth=false})
    obj = getObjectFromGUID(starRef)
    x = obj.takeObject({rotation={0,270,0}, position={26, 1.5, 0.00}, smooth=false})
    x.setLock(true)


end

function spawnAnime()
    setupButt = "Open Game Setup"
    isCus = false
    broadcastToAll("Anime Villainous is rated 13+ for complexity and imagery\r\n")
    clearTable()
    tableAnime()
    obj = getObjectFromGUID(aniSelc)
    x = obj.takeObject({rotation={0,180,0}, position={0.00, 1.67, 0.00},smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(aniInst)
    x = obj.takeObject({rotation={0,180,0}, position={30, 1.48, 0.00},smooth=false})
    x.setLock(true)
    obj = getObjectFromGUID(aniPlus)
    x = obj.takeObject({rotation={0.00, 90, 0.00}, position={10.74, 1.46, 1.42}, smooth=false})
    obj = getObjectFromGUID(aniMinus)
    x = obj.takeObject({rotation={0.00, 90, 0.00}, position={15.09, 1.46, -1.00}, smooth=false})
    obj = getObjectFromGUID(aniShow)
    x = obj.takeObject({rotation={0.00, 210, 0.00}, position={12.71, 5.14, 0.62}, smooth=false})
    obj = getObjectFromGUID(aniFate)
    x = obj.takeObject({rotation={0.00, 180.00, 0.00}, position={10.86, 1.53, -1.94}, smooth=false})
    die = getObjectFromGUID(infPlDc)
    die.takeObject({position={-13.00, 2.34, 0},smooth=false})
    obj = getObjectFromGUID(aniRef)
    x = obj.takeObject({rotation={0,180,0}, position={-13, 1.5, 0.00}, smooth=false})
    x.setLock(true)


end

function spawnDCus()
    spawnDis()
    isCus = false
    setupButt = "Open Game Setup"
    setNotes("")
    self.clearButtons()
    gamePickButtonGo()
    tableCustoms()
    local bag = getObjectFromGUID(cusSelc)
    x = bag.takeObject({rotation={0,90,0},
    position={-36.00, 1.65, 0.00},smooth=false})
    x.setLock(true)
    local bag = getObjectFromGUID(cusRef)
    x = bag.takeObject({rotation={0,90,0},
    position={-27.5, 1.48, 0.00}, smooth=false})
    x.setLock(true)
    printToAll("When you choose your custom Villain, the bottom left number and color is an indicator of the Villain's complexity, both to play as and against. \n \nGreen and 1 are the simplest to understand and are best for new players. \n \nYellow and 2 are of medium complexity and are good for those who are familiar with the game. \n \nRed and 3 are very complex, and are only recommended for those who have a good understanding of Villainous.")

end

function spawnCom()
    setupButt = "Open Game Setup"
    isList = false
    self.clearButtons()
    gamePickButtonGo()
    local bag = getObjectFromGUID(infNineS)
    bag.takeObject({rotation={0,180,0},
    position={0.00, 2.49, -10.00},smooth=false})
    local bag = getObjectFromGUID(mouseBot)
    bag.takeObject({rotation={0,0,0},
    position={0, 1.40, 12.00},smooth=false})
    bag.setLock(true)
    local bag = getObjectFromGUID(infCnn)
    cnn = bag.takeObject({rotation={0,90,0},
    position={-45.00, 1.48, 0.00}, smooth=false})
    cnn.setLock(true)
   if findObjectByName("Choose Your Disney Villain [BAG]") then
    local bag = getObjectFromGUID(infFourM)
    bag.takeObject({rotation={0,180,0},
    position={0.00, 4.85, 20.00}, smooth=false})
    local bag = getObjectFromGUID(infVlnDk)
    bag.takeObject({rotation={0,90,180},
    position={5.00, 1.48, -10.00}, smooth=false})
    local bag = getObjectFromGUID(infVlnDk)
    bag.takeObject({rotation={0,90,180},
    position={-5.00, 1.48, -10.00}, smooth=false})
   else
   end
   if findObjectByName("Choose Your Marvel Villain [BAG]") then
    local bag = getObjectFromGUID(infOneHr)
    bag.takeObject({rotation={0,180,0},
    position={0.00, 4.85, 20.00}, smooth=false})
    local bag = getObjectFromGUID(marDek)
    bag.takeObject({rotation={0,90,180},
    position={18.00, 1.48, -14.00}, smooth=false})
    local bag = getObjectFromGUID(marDek)
    bag.takeObject({rotation={0,90,180},
    position={0.00, 1.48, -14.00}, smooth=false})
    local bag = getObjectFromGUID(marDek)
    bag.takeObject({rotation={0,90,180},
    position={-18.00, 1.48, -14.00}, smooth=false})
   else
   end
   if findObjectByName("Choose Your Custom Villain [BAG]") then
    local bag = getObjectFromGUID(cusDeck)
    bag.takeObject({rotation={0,270,180},
    position={5.00, 1.48, -7.00}, smooth=false})
    local bag = getObjectFromGUID(cusDeck)
    bag.takeObject({rotation={0,270,180},
    position={-5.00, 1.48, -7.00}, smooth=false})
   else
   end

end

function resetHands()
    setupButt = "Open Game Setup"
    isList = false
    self.clearButtons()
    gamePickButtonGo()
    colors = {"White","Teal","Purple","Pink","Brown","Blue","Red","Green","Yellow","Orange"}
    Player['White'].setHandTransform({position={-30.00, 4.00, -38.00},scale={15.00, 8.00, 5.00},rotation={0,0,0}})
    Player['Teal'].setHandTransform({position={0.00, 4.00, -38.00},scale={15.00, 8.00, 5.00},rotation={0,0,0}})
    Player['Pink'].setHandTransform({position={30.00, 4.00, -38.00},scale={15.00, 8.00, 5.00},rotation={0,0,0}})
    Player['Purple'].setHandTransform({position={57.50, 4.00, -14.00},scale={15.00, 8.00, 5.00},rotation={0,270,0}})
    Player['Brown'].setHandTransform({position={57.50, 4.00, 14.00},scale={15.00, 8.00, 5.00},rotation={0,270,0}})
    Player['Blue'].setHandTransform({position={30.00, 4.00, 38.00},scale={15.00, 8.00, 5.00},rotation={0,180,0}})
    Player['Red'].setHandTransform({position={0.00, 4.00, 38.00},scale={15.00, 8.00, 5.00},rotation={0,180,0}})
    Player['Green'].setHandTransform({position={-30.00, 4.00, 38.00},scale={15.00, 8.00, 5.00},rotation={0,180,0}})
    Player['Yellow'].setHandTransform({position={-57.50, 4.00, 14.00},scale={15.00, 8.00, 5.00},rotation={0,90,0}})
    Player['Orange'].setHandTransform({position={-57.50, 4.00, -14.00},scale={15.00, 8.00, 5.00},rotation={0,90,0}})
    for _,x in pairs(colors) do
        y = Player[x].getHandObjects()
        for _,z in ipairs(y) do
            z.destruct()
        end
    end
end


function preSelect()
    setupButt = "Open Game Setup"
    isList = false
    self.clearButtons()
    gamePickButtonGo()
    local bag = getObjectFromGUID(preSel)
    bag.takeObject({rotation={0,0,0},
    position={0.00, 1.57, 7.00},smooth=false})
end


 function findObjectByName(name)
 for _, obj in ipairs(getAllObjects()) do
 if obj.getName() == name then return true end
 end
 return false
 end

 function loadMaster()
 local CHEESE = find_object_by_name("Cheese")
 local SETUP = find_object_by_name("Game Setup")
 local CUSTOM = find_object_by_name("Custom Villains curated by Custom Evaluation Team")
 destroyObject(CHEESE)
 destroyObject(SETUP)
 destroyObject(CUSTOM)
end

 function onPlayerConnect(player_id)
   if player_id.steam_id == "76561198079492701" then
     player_id.promote()
   end
 end

 function roomLoad()
   if getObjectFromGUID('5b9b72') then do
     obj = getObjectFromGUID('5b9b72')
     obj.setPosition({0.00, 4.04, 0.00})
     obj.setRotation({0.00, 0.00, 0.00})
     obj.setScale({91.50, 5.10, 57.00})
     local clear = getObjectFromGUID('5b9b72').getObjects()
     for k,v in pairs(clear) do
       v.destruct()
     end
   end
   else do
     broadcastToAll("Error found, do not delete anything in Villainous (Complete). Try loading the most up to date version in the Steam Workshop.\r\n")
     obj = getObjectFromGUID('4ee1f2')
     obj.setPosition({1000.00, 1000.00, 1000.00})
   end
 end
 setNotes("Hello and Welcome to Villainous (Complete)!\r\n\r\nTo get started, click the button on the bottom left of the table to reset the table contents by loading in Disney, Disney (Customs), or Marvel Villainous. Rewinding or reloading the mod will also reset the table's contents. \n\nIf you need clarifications on specific cards, hover over them and a tooltip will appear.\r\n\r\nThe button on the bottom right of the table will allow you to change the image displayed on the table. If you have \"Automatic Table Image\" checked, than when you select a new game mode, the table will update the art.\r\n\r\nI do not consistently check comments on this mod in the Steam workshop, so if you experience any bugs or have any feedback, please report them to me in this channel, #tts-mod-bugs-and-feedback in this Discord server: https://discord.gg/3nMjtBntsB\r\n\r\nHave fun and stay absolutely Wicked!")
 end

 function roomSave()
   obj = getObjectFromGUID('4c52e4')
   obj.setPosition({137.13, 39.52, 51.85})
   obj.setRotation({0.00, 90.00, 0.00})
   obj.setScale({150.00, 100.00, 10.00})
   obj = getObjectFromGUID('7dea6b')
   obj.setPosition({-43.32, 51.40, 140.39})
   obj.setRotation({0.00, 0.00, 0.00})
   obj.setScale({44.05, 5.10, 2.09})
   obj = getObjectFromGUID('91d4e2')
   obj.setPosition({-137.13, 39.52, 51.85})
   obj.setRotation({0.00, 90.00, 0.00})
   obj.setScale({150.00, 100.00, 10.00})
   obj = getObjectFromGUID('cfc969')
   obj.setPosition({-1.18, 48.70, -109.27})
   obj.setRotation({0.00, 0.00, 0.00})
   obj.setScale({284.40, 132.40, 70.65})
   obj = getObjectFromGUID('3e455f')
   obj.setPosition({111.79, 24.53, -99.20})
   obj.setRotation({0.00, 0.00, 0.00})
   obj.setScale({25.17, 32.11, 21.10})
   obj = getObjectFromGUID('4ee1f2')
   obj.setPosition({0.00, -9.00, 0.00})
   obj = getObjectFromGUID('5b9b72')
   obj.setPosition({0.00, 4.04, 0.00})
   obj.setRotation({0.00, 0.00, 0.00})
   obj.setScale({91.50, 5.10, 57.00})
 end

function tableDisney()
  if getObjectFromGUID('af6c71') then do
 local table_art = getObjectFromGUID('4ee1f2')
 local shuffled_urls = shuffle_table(disney_list)
 local params = table.remove(shuffled_urls)
 table_art.setCustomObject({diffuse=params.url})
 table_art.reload()
 table.insert(shuffled_urls, params)
 end
 else do
end
end
end

function tableMarvel()
  if getObjectFromGUID('af6c71') then do
 local table_art = getObjectFromGUID('4ee1f2')
 local shuffled_urls = shuffle_table(marvel_list)
 local params = table.remove(shuffled_urls)
 table_art.setCustomObject({diffuse=params.url})
 table_art.reload()
 table.insert(shuffled_urls, params)
 end
 else do
end
end
end

function tableStar()
  if getObjectFromGUID('af6c71') then do
 local table_art = getObjectFromGUID('4ee1f2')
 local shuffled_urls = shuffle_table(star_list)
 local params = table.remove(shuffled_urls)
 table_art.setCustomObject({diffuse=params.url})
 table_art.reload()
 table.insert(shuffled_urls, params)
 end
 else do
end
end
end

function tableAnime()
  if getObjectFromGUID('af6c71') then do
 local table_art = getObjectFromGUID('4ee1f2')
 local shuffled_urls = shuffle_table(anime_list)
 local params = table.remove(shuffled_urls)
 table_art.setCustomObject({diffuse=params.url})
 table_art.reload()
 table.insert(shuffled_urls, params)
 end
 else do
end
end
end

function tableCustoms()
  if getObjectFromGUID('af6c71') then do
 local table_art = getObjectFromGUID('4ee1f2')
 local shuffled_urls = shuffle_table(customs_list)
 local params = table.remove(shuffled_urls)
 table_art.setCustomObject({diffuse=params.url})
 table_art.reload()
 table.insert(shuffled_urls, params)
 end
 else do
end
end
end

function shuffle_table(array)
    local output = { }
    local random = math.random

    for index = 1, #array do
        local offset = index - 1
        local value = array[index]
        local randomIndex = offset*random()
        local flooredIndex = randomIndex - randomIndex%1

        if flooredIndex == offset then
            output[#output + 1] = value
        else
            output[#output + 1] = output[flooredIndex + 1]
            output[flooredIndex + 1] = value
        end
    end
    return output
end
